### ISSUE TITLE
希望可以提供水印覆写攻击测试的代码

### ISSUE THREAD

**Issue by cys-china** [eil/greedy-residuals#3]
我试图通过不同超参、密钥及水印信息重复训练同一模型进行水印覆写攻击测试。但测试结果与文章有较大偏差。我不确定是否错误理解了该攻击，希望能够提供水印覆写攻击测试的代码重新测试，感激不尽。

**Comment by eil** [comment]
Hello. Thanks for your attention. Currently, we do not plan to release additional codes other than this codebase. If it is convenient, please send me the details via email. I will help you check your codes and try to figure out what is going on. Thanks!
