### ISSUE TITLE
The code of ICML2023 paper Trapdoor Normalization with Irreversible Ownership Verification

### ISSUE THREAD

**Issue by TIEHua** [eil/greedy-residuals#4]
Hi, thank you for open source code, I recently read your ICML2023 paper 'Trapdoor Normalization with Irreversible Ownership Verification'. Do you have any plans to release the code of this paper?

**Comment by eil** [comment]
Thanks for your interest in our other research work! It is in progress. I am going to close this issue because it is irrelevant to this ICML 2021 project. Please feel free to contact me via email if there is anything I can help you with concerning our ICML 2023 research work!
