### ISSUE TITLE
Overwrite experiments

### ISSUE THREAD

**Issue by yyyaoyuan** [eil/greedy-residuals#5]
Hi, could you tell me the details of the overwrite experiments? Why can you overwrite a new watermark without using a dataset?

**Comment by eil** [comment]
> Hello. Thanks for your attention. Currently, we do not plan to release additional codes other than this codebase. If it is convenient, please send me the details via email. I will help you check your codes and try to figure out what is going on. Thanks!

https://github.com/eil/greedy-residuals/issues/3#issuecomment-1505114379
